repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: detect-private-key

  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: yarn eslint --fix
        language: node
        types: [javascript, typescript]
        require_serial: true

      - id: prettier
        name: Prettier
        entry: yarn prettier --write
        language: node
        types_or: [javascript, typescript, json, yaml, markdown]

      - id: type-check
        name: TypeScript Type Check
        entry: yarn type-check
        language: node
        pass_filenames: false
        types: [typescript]